services:
  mysql-db:
    image: mysql:8.4
    container_name: stockflow-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: stockflow_db
      MYSQL_USER: stockflow_user
      MYSQL_PASSWORD: stockflow_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
