# URL con parámetros de compatibilidad para MySQL 8+
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/stockflow_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC

spring.datasource.username=stockflow_user
spring.datasource.password=stockflow_pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate (Recuerda NO poner el dialecto manual)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# spring.jpa.properties.hibernate.type.preferred_uuid_jdbc_type=BINARY

# Opcional: Ayuda a ver qué está pasando con los parámetros de las consultas
logging.level.org.hibernate.orm.jdbc.bind=trace